print('👍'*5,"WHOLESOME POSITIVITY MACHINE ",'🎉'*5)
name = input("what is your name? :")
achievement = input("what do you want to achieve? :")
mood = int(input("on a scale of 1-10, how do you feel today.. \n1🤕 10😁\n:"))
print(" Just know that \n WHEN THE GOING GETS TOUGH\nTHE TOUGH GETS GOING" )
print(f" HEY {name}, keep you chin up! Today you are going to {achievement} in a way you have never done before\nI JUST WANT TO LET YOU KNOW -YOU ROCK")
